name: API Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and run tests
        run: |
          ./gradlew clean test --info
          ./gradlew allureReport

      - name: Upload Allure results
        uses: allure-framework/allure-github-actions@v1.0.3
        with:
          directory: build/allure-results

      - name: Upload Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/allure-report
