name: API Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Pipeline Secret Variables
        run: |
          cat > src/main/resources/authorization.properties << EOF
          authorization = ${{ secrets.AUTH_TOKEN }}
          username = ${{ secrets.USERNAME }}
          password = ${{ secrets.PASSWORD }}
          EOF

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Swagger models
        run: ./gradlew openApiGenerate

      - name: Build and Run Tests
        run: ./gradlew test

      - name: Generate Allure Report
        run: ./gradlew allureReport
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
